// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnK9XPlb_Vc_SeDm9ltyGi8ohEsghag5w',
    appId: '1:714684462285:web:1e2cabd7e9fc0844de6584',
    messagingSenderId: '714684462285',
    projectId: 'myapp-2df2f',
    authDomain: 'myapp-2df2f.firebaseapp.com',
    storageBucket: 'myapp-2df2f.appspot.com',
    measurementId: 'G-FE849HLSGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQkGeK3gF8NZOI8C_Tfz7mRv4Ks6Fti4',
    appId: '1:714684462285:android:d88e15009d534b4ade6584',
    messagingSenderId: '714684462285',
    projectId: 'myapp-2df2f',
    storageBucket: 'myapp-2df2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTJQzEfwGp4lTT7s48aMAhIQ4AohsS9k',
    appId: '1:714684462285:ios:a26ffe53b1759342de6584',
    messagingSenderId: '714684462285',
    projectId: 'myapp-2df2f',
    storageBucket: 'myapp-2df2f.appspot.com',
    androidClientId: '714684462285-kqsppgpgpcm1eedrd0ghb42eructj4dg.apps.googleusercontent.com',
    iosClientId: '714684462285-mn06hud4rjd9vfi709lg5mpomr6ohr54.apps.googleusercontent.com',
    iosBundleId: 'com.cgg.gov.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFTJQzEfwGp4lTT7s48aMAhIQ4AohsS9k',
    appId: '1:714684462285:ios:a26ffe53b1759342de6584',
    messagingSenderId: '714684462285',
    projectId: 'myapp-2df2f',
    storageBucket: 'myapp-2df2f.appspot.com',
    androidClientId: '714684462285-kqsppgpgpcm1eedrd0ghb42eructj4dg.apps.googleusercontent.com',
    iosClientId: '714684462285-mn06hud4rjd9vfi709lg5mpomr6ohr54.apps.googleusercontent.com',
    iosBundleId: 'com.cgg.gov.flutterProject',
  );
}
